#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tkarri <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/02 20:10:21 by tkarri            #+#    #+#              #
#    Updated: 2019/04/02 20:10:45 by tkarri           ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file

FLAGS = gcc -Wall -Werror -Wextra -o

FILES = main.c functions.c

all:
	@$(FLAGS) $(NAME) $(FILES)

clean:
	@/bin/rm -f *.o
fclean:
	@/bin/rm -f $(NAME)